"""empty message

<<<<<<<< HEAD:migrations/versions/01569cd03f1b_.py
Revision ID: 01569cd03f1b
Revises: 
Create Date: 2025-02-12 17:50:43.929371
========
Revision ID: 6617d3a6ed27
Revises: 
Create Date: 2025-02-13 14:02:06.479558
>>>>>>>> 3e51498 (funciones de obtener datos cliente hecha):migrations/versions/6617d3a6ed27_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/01569cd03f1b_.py
revision = '01569cd03f1b'
========
revision = '6617d3a6ed27'
>>>>>>>> 3e51498 (funciones de obtener datos cliente hecha):migrations/versions/6617d3a6ed27_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('trainer', 'client', name='role_enum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('goal', sa.Enum('gain', 'lose', name='goal_enum'), nullable=True),
    sa.Column('goal_kg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('abdomen', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('leg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.drop_table('plan')
    op.drop_table('user')
    # ### end Alembic commands ###
